# Generated by Django 3.1.2 on 2020-10-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
