# Generated by Django 3.1.2 on 2020-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiet', '0002_scoreboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
